### ISSUE TITLE
USER STORY: Poll on home page

### ISSUE THREAD

**Issue by alphabetjim** [alphabetjim/love-running-alt-template#1]
In order to **gain feedback from users** as a **site administrator**, I can **include a poll on the site home page.**

### Acceptance Criteria ###

- Home page features a form containing elements that allow the user to enter their level of enjoyment, as well as a text area for further comment.
- Once satisfied with their input, a button is present to allow submission.

### Tasks ###

- [ ] Task 1: Create a form within the home page, formatted to fit in with the site theme, with fields for several questions and a multiple-choice radio button entry format. Also include a textarea for further comment.
- [ ] Task 2: Add a submit button to the form, which changes colour once used.
- [ ] Task 3: Update unit test scripts.
- [ ] Task 4: Test the functionality.
