### ISSUE TITLE
USER STORY: User anonymity

### ISSUE THREAD

**Issue by alphabetjim** [alphabetjim/love-running-alt-template#2]
In order to **preserve my anonymity** as a **user**, I can **choose to vote anonymously.**

### Acceptance Criteria: ###

- A checkbox should be available to enable users to request anonymity.
- When checked, this should mute or hide any user detail entry fields.
- A message should display to confirm that the poll is being filled out anonymously.

### Tasks ###

- [ ] Task 1: Add a checkbox to the poll, labelled to indicate that responses are anonymous if it is checked.
- [ ] Task 2: Make this checked by default.
- [ ] Task 3: Set CSS up so that checking the anonymity checkbox causes a message e.g. "Your responses to this poll will be recorded anonymously" to display next to the submit button.
- [ ] Task 4: Use CSS to grey-out the email & password entry fields, and either disregard any data entered or block data entry within them.
- [ ] Task 5: Update unit test scripts.
- [ ] Task 6: Test the functionality.
