### ISSUE TITLE
USER STORY: Poll result recording

### ISSUE THREAD

**Issue by alphabetjim** [alphabetjim/love-running-alt-template#3]
In order to **keep track of feedback** as a **site administrator**, I can **keep a record of previous polls.**

### Acceptance Criteria ###

- Site administrator should have access to a section containing previous polls.
- Each poll would show the available options and the results for these.

### Tasks ###

- [ ] Task 1: Create page to show the previous polls, showing each under its own heading.
- [ ] Task 2: Set up the sections to contain the results of each of the previous polls, displayed as a bar chart.
- [ ] Task 3: Make a link to connect to this, displaying adjacent to the heading of the current poll on the home page.
- [ ] Task 4: Update unit test scripts.
- [ ] Task 5: Test the functionality.
