### ISSUE TITLE
USER STORY: Poll result detail

### ISSUE THREAD

**Issue by alphabetjim** [alphabetjim/love-running-alt-template#4]
In order to **gain more insight into user feedback** as a **site administrator**, I can **see a detailed breakdown of voting on all polls.**

### Acceptance Criteria: ###
- Acceptance criterion 1: website administrator should be able to see responses to each question as totals.
- Acceptance criterion 2: website administrator should be able to see (for non-anonymous users) who gave which response to each question.
- Acceptance criterion 3: This information should not be visible to other users.

### Tasks ###
- [ ] Task 1: Create a table with columns for each response option and the users who voted for it.
- [ ] Task 2: Implement password protection on this, so that only a logged-in site manager can access the page.
- [ ] Task 3: Update unit test scripts.
- [ ] Task 4: Test the functionality.
